In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## 텐서 제어하기

### 텐서 생성하기

- PyTorch 텐서는 `torch.tensor()`를 활용하여 생성한다.
- https://pytorch.org/docs/stable/tensors.html

### 텐서의 종류

|이름|정의|차원|표기법|
|:--------:|:--------:|:--------:|:--------:|
| Scalar | 단일 숫자|0|a|
| Vector | 방향이 포함된 숫자 | 1 | y |
| Matrix | 2차원 숫자 배열 | 2 | Q |
| Tensor | N-차원의 숫자 배열 | 어떤 숫자든 나올 수 있음 | X |

### 텐서와 이미지
- shape : (channel, height, wdith)

In [ ]:
# 1. 스칼라 
scalar = torch.tensor(7)
# 2. 벡터
vector = torch.tensor([7,7])
# 3. 행렬
matrix = torch.tensor([[1,5],[5,1]])
# 4. 텐서
tensor = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]]])

print(f"[스칼라] 차원 : {scalar.ndim}, 형상 : {scalar.shape}")
print(f"[벡터] 차원 : {vector.ndim}, 형상 : {vector.shape}")
print(f"[행렬] 차원 : {matrix.ndim}, 형상 : {matrix.shape}")
print(f"[텐서] 차원 : {tensor.ndim}, 형상 : {tensor.shape}")

[스칼라] 차원 : 0, 형상 : torch.Size([])
[벡터] 차원 : 1, 형상 : torch.Size([2])
[행렬] 차원 : 2, 형상 : torch.Size([2, 2])
[텐서] 차원 : 3, 형상 : torch.Size([1, 3, 3])


### 랜덤 텐서

- 신경망 학습을 하는 수많은 텐서들은 랜덤 텐서값을 초기값으로 사용함

In [5]:
# 랜덤 텐서 생성하기
random_tensor = torch.rand(size=(2, 2, 2))
print(f"값 : {random_tensor} / 차원 수 : {random_tensor.ndim} / 형태 : {random_tensor.shape}")

값 : tensor([[[0.8127, 0.4500],
         [0.6004, 0.3446]],

        [[0.3192, 0.6401],
         [0.5159, 0.8884]]]) / 차원 수 : 3 / 형태 : torch.Size([2, 2, 2])


### 텐서 초기화

- 1 또는 0으로 초기화 하는 방법

In [17]:
zeros = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))
zeros, ones

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

### 특정 범위의 텐서 생성하기

In [6]:
print(torch.arange(start=1, end=11, step=2))
print(torch.arange(start=1, end=11))

tensor([1, 3, 5, 7, 9])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


### 기존 텐서의 형태와 같은 또다른 텐서 생성하기

In [7]:
one_to_ten = torch.arange(start=1, end=11)
torch.zeros_like(input=one_to_ten)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### 텐서 데이터 유형

In [33]:
torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16).dtype
torch.tensor([3.0, 6.0, 9.0], dtype=torch.float32).dtype
torch.tensor([3.0, 6.0, 9.0], dtype=torch.float64).dtype
torch.tensor([3.0, 6.0, 9.0], 
             dtype=torch.float64,
             device="cuda",
             requires_grad=False)

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float64)

### 텐서 연산법

- 덧셈
- 뺄셈
- 곱셈(element-wise)
- 나눗셈
- 행렬곱

In [8]:
print(torch.ones(size=[2,5]) * 10)
print(torch.ones(size=[2,5]) + 10)
print(torch.ones(size=[2,5]) - 10)
print(torch.ones(size=[2,5]) / 10)
t1 = torch.ones(size=[2,5])
print(torch.add(t1, 10))
print(torch.mul(t1, 10))
print(torch.div(t1, 10))
print(torch.sub(t1, 10))

tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]])
tensor([[11., 11., 11., 11., 11.],
        [11., 11., 11., 11., 11.]])
tensor([[-9., -9., -9., -9., -9.],
        [-9., -9., -9., -9., -9.]])
tensor([[0.1000, 0.1000, 0.1000, 0.1000, 0.1000],
        [0.1000, 0.1000, 0.1000, 0.1000, 0.1000]])
tensor([[11., 11., 11., 11., 11.],
        [11., 11., 11., 11., 11.]])
tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]])
tensor([[0.1000, 0.1000, 0.1000, 0.1000, 0.1000],
        [0.1000, 0.1000, 0.1000, 0.1000, 0.1000]])
tensor([[-9., -9., -9., -9., -9.],
        [-9., -9., -9., -9., -9.]])


In [11]:
# 1. Element-wise 곱셈 방법
t1 = torch.ones(size=[2,2]).add(10)
t2 = torch.ones(size=[2,2]).add(-10)
print(torch.mul(t1, t2))
print(t1 * t2)
# 2. 행렬곱
print(torch.matmul(t1, t2))

tensor([[-99., -99.],
        [-99., -99.]])
tensor([[-99., -99.],
        [-99., -99.]])
tensor([[-198., -198.],
        [-198., -198.]])


### 크기 제어, 병합, 스퀴징

- Reshape : 입력 텐서의 크기를 변경
- View : 입력 텐서의 형태를 변경. 단, 메모리 구조는 유지
- Stacking : 여러 텐서들을 병합
- Squeeze : 크기가 1인 차원을 제거
- Unsqueeze : 입력 텐서에 1 차원을 추가
- Permute : 차원 간 형상을 변경

In [ ]:
t1 = torch.ones(size=(2,4,1))
# 1. Squeeze
print(f"원본 : {t1.shape}, Squeeze : {torch.squeeze(t1).shape}")
# 2. 

원본 : torch.Size([2, 4, 1]), Squeeze : torch.Size([2, 4])
