In [4]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## 텐서 제어하기

### 텐서 생성하기

- PyTorch 텐서는 `torch.tensor()`를 활용하여 생성한다.
- https://pytorch.org/docs/stable/tensors.html

### 텐서의 종류

|이름|정의|차원|표기법|
|:--------:|:--------:|:--------:|:--------:|
| Scalar | 단일 숫자|0|a|
| Vector | 방향이 포함된 숫자 | 1 | y |
| Matrix | 2차원 숫자 배열 | 2 | Q |
| Tensor | N-차원의 숫자 배열 | 어떤 숫자든 나올 수 있음 | X |

### 텐서와 이미지
- shape : (channel, height, wdith)

In [5]:
scalar = torch.tensor(7)
print(f"값 : {scalar}, 실제 내부 값 : {scalar.item()}")
print(f"원본 타입 : {type(scalar)}, 값 타입 : {type(scalar.item())}")
print(f"차원 : {scalar.ndim}")

값 : 7, 실제 내부 값 : 7
원본 타입 : <class 'torch.Tensor'>, 값 타입 : <class 'int'>
차원 : 0


In [6]:
vector = torch.tensor([7,7])
print(f"데이터 차원 : {vector.ndim}, 데이터 형태 : {vector.shape}")

데이터 차원 : 1, 데이터 형태 : torch.Size([2])


In [7]:
matrix = torch.tensor([[1,5],[5,1]])
print(f"데이터 차원 : {matrix.ndim}, 데이터 형태 : {matrix.shape}")

데이터 차원 : 2, 데이터 형태 : torch.Size([2, 2])


In [8]:
tensor = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]]])
print(f"데이터 차원 : {tensor.ndim}, 데이터 형태 : {tensor.shape}")
print(tensor[0])

데이터 차원 : 3, 데이터 형태 : torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


### 랜덤 텐서

- 신경망 학습을 하는 수많은 텐서들은 랜덤 텐서값을 초기값으로 사용함

In [14]:
# 랜덤 텐서 생성하기
random_tensor = torch.rand(2, 2, 2)
print(f"값 : {random_tensor} / 차원 수 : {random_tensor.ndim} / 형태 : {random_tensor.shape}")

값 : tensor([[[0.5482, 0.1415],
         [0.1330, 0.4118]],

        [[0.6701, 0.1912],
         [0.9959, 0.8015]]]) / 차원 수 : 3 / 형태 : torch.Size([2, 2, 2])


In [15]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### 텐서 초기화

- 1 또는 0으로 초기화 하는 방법

In [17]:
zeros = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))
zeros, ones

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

### 특정 범위의 텐서 생성하기

In [27]:
print(torch.arange(start=1, end=11, step=2))
print(torch.arange(start=1, end=11))
one_to_ten = torch.arange(start=1, end=11)

tensor([1, 3, 5, 7, 9])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


### 기존 텐서의 형태와 같은 또다른 텐서 생성하기

In [22]:
torch.zeros_like(input=one_to_ten)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 텐서 데이터 유형

In [33]:
torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16).dtype
torch.tensor([3.0, 6.0, 9.0], dtype=torch.float32).dtype
torch.tensor([3.0, 6.0, 9.0], dtype=torch.float64).dtype
torch.tensor([3.0, 6.0, 9.0], 
             dtype=torch.float64,
             device="cuda",
             requires_grad=False)

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float64)

### 텐서 연산법

- 덧셈
- 뺄셈
- 곱셈(element-wise)
- 나눗셈
- 행렬곱

In [38]:
print(torch.ones(size=[2,5]) * 10)
print(torch.ones(size=[2,5]) + 10)
print(torch.ones(size=[2,5]) - 10)
print(torch.ones(size=[2,5]) / 10)

tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]])
tensor([[11., 11., 11., 11., 11.],
        [11., 11., 11., 11., 11.]])
tensor([[-9., -9., -9., -9., -9.],
        [-9., -9., -9., -9., -9.]])
tensor([[0.1000, 0.1000, 0.1000, 0.1000, 0.1000],
        [0.1000, 0.1000, 0.1000, 0.1000, 0.1000]])


In [41]:
t1 = torch.ones(size=[2,5])
print(torch.add(t1, 10))
print(torch.mul(t1, 10))
print(torch.div(t1, 10))
print(torch.sub(t1, 10))

tensor([[11., 11., 11., 11., 11.],
        [11., 11., 11., 11., 11.]])
tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]])
tensor([[0.1000, 0.1000, 0.1000, 0.1000, 0.1000],
        [0.1000, 0.1000, 0.1000, 0.1000, 0.1000]])
tensor([[-9., -9., -9., -9., -9.],
        [-9., -9., -9., -9., -9.]])


In [50]:
# Element-wise 곱셈 방법
torch.mul(torch.ones(size=[2,2]), 10)

t1 = torch.ones(size=[2,2]).add(10)
t2 = torch.ones(size=[2,2]).add(-10)
print(t1 * t2)
print(torch.matmul(t1, t2))

tensor([[-99., -99.],
        [-99., -99.]])
tensor([[-198., -198.],
        [-198., -198.]])


### 크기 제어, 병합, 스퀴징

- Reshape : 입력 텐서의 크기를 변경
- View : 입력 텐서의 형태를 변경. 단, 메모리 구조는 유지
- Stacking : 여러 텐서들을 병합
- Squeeze : 크기가 1인 차원을 제거
- Unsqueeze : 입력 텐서에 1 차원을 추가
- Permute : 차원 간 형상을 변경

In [56]:
t1 = torch.ones(size=[2,4])
print(torch.squeeze(t1))
print(t1.permute(1,0))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
